matrix:
  include:
  - language: node_js
    stage: Web
    node_js:
    - stable
    before_script:
    - cd web
    - npm install
    cache:
      directories:
      - web/node_modules
    script:
    - npm test
    - npm run build
    deploy:
    - provider: s3
      access_key_id: AKIAJGLMJSQ5HROL7PTQ
      secret_access_key:
        secure: Xd6dEKIV6PS8dpZnG234m0R/9OE0Niqz/1kxGDvH2k4sRY0l3yF4WGf3DPvxI5I0jRuJuA/bFgAcGkhvhUG2wmTUawM58TO4jnDkQlSlj5pXuGRiyJiSVxnanRSp63dbfNDM7KCw8M1Tw5XQXKZVUynzbne/EeYs/c+jyAIX8OMMyHMPm1wE5m/cYiAl97AePlLtJhFB0hxG4GbmzNqiBHSuppPViY63wnfv0sfs0leXnPZ9UNEahfbuuFWymZxvJTmpdD5/4UrAw68C7GH8IQ5Z+2oWIlooTteNiDyNiFzX4aCKZ6SfQJAH+HInpPDfR2LKi0xKChb2RLccvW3FnCENyEihNYmELE0uiGHrELBIBZXWFH/8qH+2+4nOWuhEGhmdywTOpIYdOrXTpwxsMCc+42eD12NNeGFRSoOu+nqsDl3ifI3C0ZYrKYb70i78IlAcnki68UwWhvJhSA9TymwXV4INhiiTE3TQhw9duwlwMnxk+PTIhBt2tEjggDIcjCc75r6GTYdhex/r/PEYBL24qVM82GHeOKz0u4Ew85XpU/W9BwKu7tFzI8pxow8F0UCoKkcqDfNioqFx91qmrimFh5Z0GAsh4honixBWqEzBhKRVBNkHVrJ23PxPQBoX8n7EI7ehXGPnb2rVvcSkoQkHsl8NmYZkjYviv2y9ezc=
      bucket: qcvoc-prod
      skip_cleanup: true
      local_dir: build
      region: us-east-1
      acl: public_read
      on:
        repo: qccoders/QCVOC
        branch: master
    - provider: s3
      access_key_id: AKIAJGLMJSQ5HROL7PTQ
      secret_access_key:
        secure: Xd6dEKIV6PS8dpZnG234m0R/9OE0Niqz/1kxGDvH2k4sRY0l3yF4WGf3DPvxI5I0jRuJuA/bFgAcGkhvhUG2wmTUawM58TO4jnDkQlSlj5pXuGRiyJiSVxnanRSp63dbfNDM7KCw8M1Tw5XQXKZVUynzbne/EeYs/c+jyAIX8OMMyHMPm1wE5m/cYiAl97AePlLtJhFB0hxG4GbmzNqiBHSuppPViY63wnfv0sfs0leXnPZ9UNEahfbuuFWymZxvJTmpdD5/4UrAw68C7GH8IQ5Z+2oWIlooTteNiDyNiFzX4aCKZ6SfQJAH+HInpPDfR2LKi0xKChb2RLccvW3FnCENyEihNYmELE0uiGHrELBIBZXWFH/8qH+2+4nOWuhEGhmdywTOpIYdOrXTpwxsMCc+42eD12NNeGFRSoOu+nqsDl3ifI3C0ZYrKYb70i78IlAcnki68UwWhvJhSA9TymwXV4INhiiTE3TQhw9duwlwMnxk+PTIhBt2tEjggDIcjCc75r6GTYdhex/r/PEYBL24qVM82GHeOKz0u4Ew85XpU/W9BwKu7tFzI8pxow8F0UCoKkcqDfNioqFx91qmrimFh5Z0GAsh4honixBWqEzBhKRVBNkHVrJ23PxPQBoX8n7EI7ehXGPnb2rVvcSkoQkHsl8NmYZkjYviv2y9ezc=
      bucket: qcvoc-dev
      skip_cleanup: true
      local_dir: build
      region: us-east-1
      acl: public_read
      on:
        repo: qccoders/QCVOC
        branch: develop
  - language: csharp
    stage: Api
    mono: none
    dotnet: 2.1
    before_script:
    - cd api
    - dotnet restore
    script:
    - dotnet build --no-restore --no-incremental
    - dotnet test QCVOC.Api.Tests.Unit/QCVOC.Api.Tests.Unit.csproj
    before_deploy:
    - dotnet publish --configuration Release
    - cd QCVOC.Api/bin/Release/netcoreapp2.1/publish
    deploy:
    - provider: lambda
      function_name: QCVOC-DEV
      region: us-east-1
      role: arn:aws:iam::620048899897:role/service-role/QCVOC-Prod-Lambda
      runtime: dotnetcore2.1
      timeout: 30
      memory_size: 256
      module_name: QCVOC.Api::QCVOC.Api
      handler_name: LambdaEntryPoint::FunctionHandlerAsync
      access_key_id: AKIAJGLMJSQ5HROL7PTQ
      secret_access_key:
        secure: Xd6dEKIV6PS8dpZnG234m0R/9OE0Niqz/1kxGDvH2k4sRY0l3yF4WGf3DPvxI5I0jRuJuA/bFgAcGkhvhUG2wmTUawM58TO4jnDkQlSlj5pXuGRiyJiSVxnanRSp63dbfNDM7KCw8M1Tw5XQXKZVUynzbne/EeYs/c+jyAIX8OMMyHMPm1wE5m/cYiAl97AePlLtJhFB0hxG4GbmzNqiBHSuppPViY63wnfv0sfs0leXnPZ9UNEahfbuuFWymZxvJTmpdD5/4UrAw68C7GH8IQ5Z+2oWIlooTteNiDyNiFzX4aCKZ6SfQJAH+HInpPDfR2LKi0xKChb2RLccvW3FnCENyEihNYmELE0uiGHrELBIBZXWFH/8qH+2+4nOWuhEGhmdywTOpIYdOrXTpwxsMCc+42eD12NNeGFRSoOu+nqsDl3ifI3C0ZYrKYb70i78IlAcnki68UwWhvJhSA9TymwXV4INhiiTE3TQhw9duwlwMnxk+PTIhBt2tEjggDIcjCc75r6GTYdhex/r/PEYBL24qVM82GHeOKz0u4Ew85XpU/W9BwKu7tFzI8pxow8F0UCoKkcqDfNioqFx91qmrimFh5Z0GAsh4honixBWqEzBhKRVBNkHVrJ23PxPQBoX8n7EI7ehXGPnb2rVvcSkoQkHsl8NmYZkjYviv2y9ezc=
      on:
        repo: qccoders/QCVOC
        branch: develop
    - provider: lambda
      function_name: QCVOC-PROD
      region: us-east-1
      role: arn:aws:iam::620048899897:role/service-role/QCVOC-Prod-Lambda
      runtime: dotnetcore2.1
      timeout: 30
      memory_size: 256
      module_name: QCVOC.Api::QCVOC.Api
      handler_name: LambdaEntryPoint::FunctionHandlerAsync
      access_key_id: AKIAJGLMJSQ5HROL7PTQ
      secret_access_key:
        secure: Xd6dEKIV6PS8dpZnG234m0R/9OE0Niqz/1kxGDvH2k4sRY0l3yF4WGf3DPvxI5I0jRuJuA/bFgAcGkhvhUG2wmTUawM58TO4jnDkQlSlj5pXuGRiyJiSVxnanRSp63dbfNDM7KCw8M1Tw5XQXKZVUynzbne/EeYs/c+jyAIX8OMMyHMPm1wE5m/cYiAl97AePlLtJhFB0hxG4GbmzNqiBHSuppPViY63wnfv0sfs0leXnPZ9UNEahfbuuFWymZxvJTmpdD5/4UrAw68C7GH8IQ5Z+2oWIlooTteNiDyNiFzX4aCKZ6SfQJAH+HInpPDfR2LKi0xKChb2RLccvW3FnCENyEihNYmELE0uiGHrELBIBZXWFH/8qH+2+4nOWuhEGhmdywTOpIYdOrXTpwxsMCc+42eD12NNeGFRSoOu+nqsDl3ifI3C0ZYrKYb70i78IlAcnki68UwWhvJhSA9TymwXV4INhiiTE3TQhw9duwlwMnxk+PTIhBt2tEjggDIcjCc75r6GTYdhex/r/PEYBL24qVM82GHeOKz0u4Ew85XpU/W9BwKu7tFzI8pxow8F0UCoKkcqDfNioqFx91qmrimFh5Z0GAsh4honixBWqEzBhKRVBNkHVrJ23PxPQBoX8n7EI7ehXGPnb2rVvcSkoQkHsl8NmYZkjYviv2y9ezc=
      on:
        repo: qccoders/QCVOC
        branch: master
  - language: android
    stage: Android
    android:
      components:
      - build-tools-28.0.2
      - android-26
      - extra-google-google_play_services
    before_script:
    - cd mobile
    script:
    - "./gradlew --quiet build"
    - openssl aes-256-cbc -K $encrypted_1d09d3d42bcc_key -iv $encrypted_1d09d3d42bcc_iv
      -in qcvoc-key.jks.enc -out qcvoc-key.jks -d
env:
  global:
  - secure: s/AUVVBdqUi+tgLJY3ljbjfYGZEjYjDDIRAR3N5tH3drR3cS542I4XtAnNtWGuhwmtCDusci/Tg4P9+UDBEjIY/MXWD+Kab3OkAhAEe8OpQwQ0t7p81S4KLlxrdnxmmoQawULBVpcXeyo8F8CD5g6XPO/nesPwC1SHrhWanxDEvAZwshIML5PcoTVrwMTHzvEjj9+ZMs+p1x2dFjFDOdJqd65Qip9ujiH9rtUVdFGb3nXgZasprTir6PQoFtIMNL0ZkMIC/uspDDUObPDpf0hiK9BK2Cv31rfhbCfdehZjWhba+foiSsU/Gwcl/M/ay4xAFncBxC9BqluW2BcKv1gakE4oYQl7sF//2DJrunHelxw0JsMxspHaw7ABrLi9LhpBIgNGiIL7ljl2ZJkKH18v6g6R9G0Xk4Rjyqa9X4Drms/lQDMvI2+Xp0WUvSV15Iy765OaWkDdsOY0+j//0JD2te2LH3NmcSOPlkWjvMO7TLWjzj0Q+JfxVUiVSsMVVO78YK431zh1Vf03TCZ/LmzXfCxyRsoFE8uxJpxrFwHir/q9fjHKsJdNQVN+dD/4jpK/oqY399EwYSLbtye4NcbdDAqZfXcY5bNTqvy3JESipR4xmp1DGcUlVh5FX7mmlEx8eT2Z2i9L09tGter9mZHn1A/9UNvycxAudY4oWPHn4=
  - secure: Lz0KdHOttf/tOlkLILVJOxtzGAQUgXWJKyULbxwy8b3/qZMLDDIcgRQESzQTfJfozRuoqqwuswataCELdQ83PwpvFdfzDA9kRd5fpF+UCZCbkFyu/SoocWJrwrXpBHEwoeg3Jw0xIqulg4TYgiJ+2E7JvR4Nc0d/IF/f3Ejk+ymkTIi4dJy9dPkZzoox96SJZJQlG0jgHxZHId9SMuyOBtzJvbt0VCl/oJu8K84x/g5oxN1K0UpNQcmSKTl4+GR/SwiD68nOMCs8Lir5aP+hS0g5mZguVfRO9l25SE7BCl6vY/Ev2TKDo+w3v2YAE8Z1+g7KGWLN8Oq9VVrx/gM6NOPDfS++GqbZpkEEUpTCGF80aPTwhc5cYlgBKj4NjcG02WNGneQENBNwbY6e/pPD+cov0FZgqn3BCBtFf5kPsCfaOS4QrxKeUaiJzlfaeWHR51AaMnObxMuQHXS48aZmunswI0RF4/G6e4FtxP59JG+6JnbT/HRK1DPdfLmoyoh2gn9PntrLUzmH3H+EvpSd9jp48uae3oE5XTslLoKIYMoTH9Kdip2IMXR52Sz89obVfJ/Op5mSIeGMhcGp1MZnZrPltvcbcryAz+lj4kGW+w8/VqE41Foxa5i0LDbmvfnbgdAwDoKH3BYwZjWwzsFy2dvAabJATrwBfqUkMQj042g=
